### ISSUE TITLE
modify for custom image input

### ISSUE THREAD

**Issue by yosun** [jtydhr88/ComfyUI-Unique3D#10]
can this be modified for custom image input

**Comment by jtydhr88** [comment]
what do you mean "modify for custom image input"? can you give more details about it?

**Comment by yosun** [comment]
user inputs their own N images instead of model generates N images from 1 input image

**Comment by jtydhr88** [comment]
if you want to use your own image, see workflow [example-workflow1](https://github.com/jtydhr88/ComfyUI-Unique3D/blob/master/workflow/example-workflow1.json) I provided.

**Comment by jtydhr88** [comment]
![image](https://github.com/jtydhr88/ComfyUI-Unique3D/assets/860985/1a6b823b-2dfd-4e0f-b935-a2e05bab755b)
this is my own image, not a generated image

**Comment by yosun** [comment]
oh, i meant to say can we input N images into the model?

**Comment by jtydhr88** [comment]
I don’t think so, the original Unique3D only accepts one input image.
Close this issue for now.
