### ISSUE TITLE
it doesn't work for me, I think there is an issue with the installed pytorch

### ISSUE THREAD

**Issue by leonnn1** [jtydhr88/ComfyUI-Unique3D#2]
The 3D pack nodes do not run for some reason, they are not even loading:

`  File "F:\AI\unique3d\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\mesh_processer\mesh.py", line 8, in <module>
    from kiui.op import safe_normalize, dot
ModuleNotFoundError: No module named 'kiui'

Cannot import F:\AI\unique3d\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'kiui'

Import times for custom nodes:
   0.0 seconds: F:\AI\unique3d\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.6 seconds (IMPORT FAILED): F:\AI\unique3d\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack`
   
   I think its because of the Pytorch versions and xformers, if I am not mistaken it requires the 2.3.1 but while installing the requirements I fails to install the 2.3.1
   
   pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1

**Comment by jtydhr88** [comment]
hi,
for the error  No module named 'kiui', you can easily fix by pip install kiui or pip install git+https://github.com/ashawkey/kiuikit.git.

it defines in https://github.com/MrForExample/ComfyUI-3D-Pack/blob/340a03babefcab1eff2f243581c116530080948d/requirements_post.txt#L10

**Comment by leonnn1** [comment]
> hi, for the error No module named 'kiui', you can easily fix by pip install kiui or pip install git+https://github.com/ashawkey/kiuikit.git.
> 
> it defines in https://github.com/MrForExample/ComfyUI-3D-Pack/blob/340a03babefcab1eff2f243581c116530080948d/requirements_post.txt#L10

I tried but I got the same error, I dont know what to do now

**Comment by jtydhr88** [comment]
have you used the correct pip to install? I mean if you are using ComfyUI embedded python (for your case, it should be F:\AI\unique3d\ComfyUI_windows_portable\python_embeded ), I think you should run 
**F:\AI\unique3d\ComfyUI_windows_portable\python_embeded\python.exe -m pip install kiui**

**Comment by leonnn1** [comment]
I copied it from the requirements itself, I also tried pip install kiui and pip install git+https.... and it didn't worked, I deleted the old env and tried to set a new one and got the same error, I did pip list and kiui is there, so I really don't get this error

**Comment by leonnn1** [comment]
I think that the problem is with the 3D pack, many users are having similar issues, I tried to fix it for hours and it simply doesn't work, I think maybe in the future the 3d Pack nodes will be working better to everyone, but for now I think many users will face similar issues as I did and it will not be easy to fix

**Comment by jtydhr88** [comment]
I think so as well.
in fact, this repo is using 3D pack to display the genereted mesh in ComfyUI:
![image](https://github.com/jtydhr88/ComfyUI-Unique3D/assets/860985/fea2f5f6-27e6-4c10-bb35-2b72215186ac)
if you don't need this feature, we could skip to install 3D-pack.

I will close this issue for now since this issue is not relevant to this repo self.
I may figure out a new requirments.txt without 3D-pack later, but anyway thanks for the feedback

**Comment by leonnn1** [comment]
> I think so as well. in fact, this repo is using 3D pack to display the genereted mesh in ComfyUI: ![image](https://private-user-images.githubusercontent.com/860985/341197910-fea2f5f6-27e6-4c10-bb35-2b72215186ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NDEyNzUsIm5iZiI6MTcxODg0MDk3NSwicGF0aCI6Ii84NjA5ODUvMzQxMTk3OTEwLWZlYTJmNWY2LTI3ZTYtNGMxMC1iYjM1LTJiNzIyMTUxODZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQyMzQ5MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTliNWQwMzhlNzJhNzI0YWU2NDgyNzYwMTQxZjE1NmExMDEzZGFkZDQ3M2VkNWFiNzViYjhkNDBmZjI4NDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GxnxTthGw3ZHnnKqZ12YZYfMlDGauMUecg22lH-61aE) if you don't need this feature, we could skip to install 3D-pack.
> 
> I will close this issue for now since this issue is not relevant to this repo self. I may figure out a new requirments.txt without 3D-pack later, but anyway thanks for the feedback

Yes, I think the issue is there, I managed to install the unique3d on its own after some hours of trial and error also, maybe its just this adaptation phase like on  the beginning of A1111, then things will be easier to use after more bugs and incompatibility warnings are solved, thank you for yoru help!

**Comment by jtydhr88** [comment]
because right now I use 3D pack to install some dependencies, so if 3D pack not installed successfully, this repo will miss dependencies as well.
