### ISSUE TITLE
这个问题怎么解决？

### ISSUE THREAD

**Issue by sherwoodwoo** [jtydhr88/ComfyUI-Unique3D#25]
Warning! extra parameter in cli is not verified, may cause erros.
You have disabled the safety checker for <class 'custum_3d_diffusion.custum_pipeline.unifield_pipeline_img2mvimg.StableDiffusionImage2MVCustomPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
RGB image not RGBA! still remove bg!
Warning! condition_latents is not None, but self_attn_ref is not enabled! This warning will only be raised once.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
!!! Exception during processing!!! auto not supported. Supported strategies are: balanced
Traceback (most recent call last):
  File "G:\ComfyUI-aki\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI-aki\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI-aki\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI-aki\custom_nodes\ComfyUI-Unique3D\run.py", line 68, in run
    pipe = load_common_sd15_pipe(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI-aki\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 107, in load_common_sd15_pipe
    pipe: StableDiffusionPipeline = model_from_ckpt_or_pretrained(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI-aki\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 44, in model_from_ckpt_or_pretrained
    pipe = model_cls.from_pretrained(ckpt_or_pretrained, torch_dtype=torch_dtype, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\unique3d-py311\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\unique3d-py311\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 677, in from_pretrained
    raise NotImplementedError(
NotImplementedError: auto not supported. Supported strategies are: balanced

**Comment by jtydhr88** [comment]
see https://github.com/AiuniAI/Unique3D/issues/24
