### ISSUE TITLE
Error occurred when executing Unique3DLoadPipeline:  auto not supported. Supported strategies are: balanced

### ISSUE THREAD

**Issue by t19922006** [jtydhr88/ComfyUI-Unique3D#26]
!!! Exception during processing!!! auto not supported. Supported strategies are: balanced
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Unique3D\run.py", line 68, in run
    pipe = load_common_sd15_pipe(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 107, in load_common_sd15_pipe
    pipe: StableDiffusionPipeline = model_from_ckpt_or_pretrained(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Unique3D\scripts\sd_model_zoo.py", line 44, in model_from_ckpt_or_pretrained
    pipe = model_cls.from_pretrained(ckpt_or_pretrained, torch_dtype=torch_dtype, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 677, in from_pretrained
    raise NotImplementedError(
NotImplementedError: auto not supported. Supported strategies are: balanced

environment
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
Loading: ComfyUI-Manager (V2.50.1)
ComfyUI Revision: 2532 [39fb74c5] *DETACHED | Released on '2024-08-13'

PIP list
accelerate                  0.33.0
aiohttp                     3.9.5
aiosignal                   1.3.1
antlr4-python3-runtime      4.9.3
attrs                       23.2.0
certifi                     2024.7.4
cffi                        1.16.0
charset-normalizer          3.3.2
click                       8.1.7
cmake                       3.30.2
colorama                    0.4.6
coloredlogs                 15.0.1
contourpy                   1.2.1
cryptography                43.0.0
cycler                      0.12.1
dataclasses-json            0.6.7
datasets                    2.21.0
Deprecated                  1.2.14
diff_gaussian_rasterization 0.0.0
diffusers                   0.30.0
dill                        0.3.8
docker-pycreds              0.4.0
einops                      0.8.0
executing                   2.0.1
filelock                    3.15.4
fire                        0.6.0
flatbuffers                 24.3.25
fonttools                   4.53.1
frozenlist                  1.4.1
fsspec                      2024.6.1
ftfy                        6.2.3
fvcore                      0.1.5.post20221221
gitdb                       4.0.11
GitPython                   3.1.43
gpytoolbox                  0.3.2
hatchling                   1.25.0
huggingface-hub             0.24.2
humanfriendly               10.0
idna                        3.7
imageio                     2.35.1
imageio-ffmpeg              0.5.1
importlib_metadata          8.3.0
intel-openmp                2021.4.0
iopath                      0.1.10
jaxtyping                   0.2.33
Jinja2                      3.1.4
jsonschema                  4.23.0
jsonschema-specifications   2023.12.1
kiui                        0.2.10
kiwisolver                  1.4.5
kornia                      0.7.3
kornia_rs                   0.1.5
lazy_loader                 0.4
lightning-utilities         0.11.6
llvmlite                    0.43.0
markdown-it-py              3.0.0
MarkupSafe                  2.1.5
marshmallow                 3.21.3
matplotlib                  3.9.2
matrix-client               0.4.0
mdurl                       0.1.2
mkl                         2021.4.0
mpmath                      1.3.0
msvc_runtime                14.40.33807
multidict                   6.0.5
multiprocess                0.70.16
mypy-extensions             1.0.0
nerfacc                     0.5.3
networkx                    3.3
ninja                       1.11.1.1
numba                       0.60.0
numpy                       1.26.4
nvdiffrast                  0.3.1
objprint                    0.2.3
omegaconf                   2.3.0
onnxruntime                 1.19.0
onnxruntime-gpu             1.19.0
open_clip_torch             2.26.1
opencv-python               4.10.0.84
opencv-python-headless      4.10.0.84
ort-nightly-gpu             1.15.0.dev20230502003
packaging                   24.1
pandas                      2.2.2
pathspec                    0.12.1
peft                        0.12.0
pillow                      10.4.0
pip                         24.2
platformdirs                4.2.2
pluggy                      1.5.0
plyfile                     1.1
pointnet2_ops               3.0.0
pooch                       1.8.2
portalocker                 2.10.1
protobuf                    5.27.3
psutil                      6.0.0
pyarrow                     17.0.0
pycparser                   2.22
pygit2                      1.15.1
PyGithub                    2.3.0
pygltflib                   1.16.2
Pygments                    2.18.0
pyhocon                     0.3.61
PyJWT                       2.9.0
PyMatting                   1.1.12
PyMCubes                    0.1.6
pymeshlab                   2023.12.post1
PyNaCl                      1.5.0
pyparsing                   3.1.2
pyreadline3                 3.4.1
python-dateutil             2.9.0.post0
pytorch-lightning           2.4.0
pytorch-msssim              1.0.0
pytorch3d                   0.7.7
pytz                        2024.1
pywin32                     306
PyYAML                      6.0.1
referencing                 0.35.1
regex                       2024.7.24
rembg                       2.0.58
requests                    2.32.3
rich                        13.7.1
rpds-py                     0.20.0
safetensors                 0.4.3
scikit-image                0.24.0
scipy                       1.14.0
sentencepiece               0.2.0
sentry-sdk                  2.13.0
setproctitle                1.3.3
setuptools                  72.1.0
shellingham                 1.5.4
simple_knn                  0.0.0
six                         1.16.0
slangtorch                  1.2.3
smmap                       5.0.1
soundfile                   0.12.1
spandrel                    0.3.4
sympy                       1.13.1
tabulate                    0.9.0
tbb                         2021.13.0
termcolor                   2.4.0
tifffile                    2024.8.10
timm                        1.0.8
tokenizers                  0.19.1
torch                       2.3.0+cu121
torch_scatter               2.1.2+pt23cu121
torchaudio                  2.3.1+cu121
torchmetrics                1.4.1
torchsde                    0.2.6
torchtyping                 0.1.5
torchvision                 0.18.0+cu121
tqdm                        4.66.4
trampoline                  0.1.2
transformers                4.43.3
trimesh                     4.4.6
trove-classifiers           2024.7.2
typeguard                   2.13.3
typer                       0.12.4
typing_extensions           4.12.2
typing-inspect              0.9.0
tzdata                      2024.1
urllib3                     1.26.19
varname                     0.13.3
wandb                       0.17.7
wcwidth                     0.2.13
wheel                       0.44.0
wrapt                       1.16.0
xatlas                      0.0.9
xformers                    0.0.26.post1
xxhash                      3.5.0
yacs                        0.1.8
yarl                        1.9.4
zipp                        3.20.0

**Comment by chunhui-l** [comment]
你好，我也是这个问题，这个是怎么解决的啊

**Comment by jtydhr88** [comment]
See https://github.com/AiuniAI/Unique3D/issues/24
