### ISSUE TITLE
whether Is the custom_nodes ComfyUI-3D-Pack must installed？

### ISSUE THREAD

**Issue by allmelgr** [jtydhr88/ComfyUI-Unique3D#30]
may i run this plugin without ComfyUI-3D-Pack？

**Comment by jtydhr88** [comment]
No, you do not need, I included 3d pack in readme because it provides a preview node, but you still can run this without 3d pack.
Btw, just I mentioned in readme as well, 3d pack also provides another implement for unique3d, so if you have some trouble with mine, you can try 3d pack as well
